// src/components/WorkoutPlan.js
import React, { Component } from 'react';
import workoutPlans from '../data/workoutPlans';

class WorkoutPlan extends Component {
  constructor() {
    super();
    this.state = {
    // Store recommended workouts here (to be generated by AI)
      recommendedWorkouts: [],
    };
  }

  // You can fetch AI-generated workout plans from an API or generate them here.

  render() {
    return (
      <div className="workout-plan">
        <h1>AI Workout Plan</h1>
        <div className="recommended-workouts">
          {this.state.recommendedWorkouts.map((workout, index) => (
            <div key={index} className="workout-card">
              <h2>{workout.title}</h2>
              <p>{workout.description}</p>
              <ul>
                {workout.exercises.map((exercise, exIndex) => (
                  <li key={exIndex}>{exercise}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default WorkoutPlan;